import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import NavigationCard from '../components/NavigationCard'
import PostFormCard from '../components/PostFormCard'
import PostCard from '../components/PostCard'

const Home: NextPage = () => {
    return (
        <div className=''>
            <Head>
                <title>Social Media Clone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='flex container mx-auto mt-4 gap-4'>
                <div className='w-1/4'>
                    <NavigationCard />
                </div>
                <div className='w-3/4'>
                    <PostFormCard />
                    <PostCard />
                </div>
            </div>
        </div>
    )
}

export default Home
