import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
    return (
        <div className=''>
            <Head>
                <title>Social Media Clone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <h1 className='text-3xl bg-green-500'>Hello world</h1>
        </div>
    )
}

export default Home
