import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import NavigationCard from '../components/NavigationCard'

const Home: NextPage = () => {
    return (
        <div className=''>
            <Head>
                <title>Social Media Clone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='flex container mx-auto mt-4 gap-4'>
                <div className='w-1/3'>
                    <NavigationCard />
                </div>
                <div className='grow'>
                    <Card>form goes here</Card>
                    posts
                </div>
            </div>
        </div>
    )
}

export default Home
